config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :destroy, :index] do
    member do
      resources :walls, only: :create
    end
  end
  resources :walls, only: [:show  , :destroy] do
    member do
      resources :posts, only: [:create]
    end
  end
  resources :sessions    , only: [:create]
  resources :friends     , only: [:create, :destroy]
  resources :participants, only: [:create, :destroy]
  match '/home'   , to: 'static_pages#home', via: 'get'
  match '/signup' , to: 'users#new'        , via: 'get'
  match '/signin' , to: 'sessions#new'     , via: 'get'
  match '/signout', to: 'sessions#destroy' , via: 'delete'

  root 'static_pages#home'

end

app/views/layouts/_header.html.erb
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to root_path do %>
                <p class="glyphicon glyphicon-home"> Home</p>
              <% end %>
            </li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if signed_in? %>
                <li>
                  <%= render 'users/search_form', name: @name %>
                </li>
                <li>
                  <%= link_to truncate(current_user.name, length: 20),
                              user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Sign out", signout_path,
                              method: :delete %>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>